cp ../../true_run/output/tst_restart_0030.nc enkf_initial_01.nc
cp ../../true_run/output/tst_restart_0031.nc enkf_initial_02.nc 
cp ../../true_run/output/tst_restart_0032.nc enkf_initial_03.nc 
cp ../../true_run/output/tst_restart_0033.nc enkf_initial_04.nc
cp ../../true_run/output/tst_restart_0014.nc enkf_initial_05.nc
cp ../../true_run/output/tst_restart_0015.nc enkf_initial_06.nc
cp ../../true_run/output/tst_restart_0016.nc enkf_initial_07.nc
cp ../../true_run/output/tst_restart_0017.nc enkf_initial_08.nc
cp ../../true_run/output/tst_restart_0018.nc enkf_initial_09.nc
cp ../../true_run/output/tst_restart_0019.nc enkf_initial_10.nc
cp ../../true_run/output/tst_restart_0020.nc enkf_initial_11.nc
cp ../../true_run/output/tst_restart_0021.nc enkf_initial_12.nc
cp ../../true_run/output/tst_restart_0022.nc enkf_initial_13.nc
cp ../../true_run/output/tst_restart_0023.nc enkf_initial_14.nc
cp ../../true_run/output/tst_restart_0024.nc enkf_initial_15.nc
cp ../../true_run/output/tst_restart_0025.nc enkf_initial_16.nc
cp ../../true_run/output/tst_restart_0026.nc enkf_initial_17.nc
cp ../../true_run/output/tst_restart_0027.nc enkf_initial_18.nc
cp ../../true_run/output/tst_restart_0028.nc enkf_initial_19.nc
cp ../../true_run/output/tst_restart_0029.nc enkf_initial_20.nc
cp ../../true_run/output/tst_restart_0034.nc enkf_initial_21.nc
