MODULE ALL_VARS
USE Mod_Spherical
LOGICAL             :: ISSpherical
LOGICAL, PARAMETER :: MSR=.TRUE.
!INTEGER, PARAMETER :: SP = SELECTED_REAL_KIND(6,30)
INTEGER, PARAMETER :: IPT = 6
   INTEGER NGL                !!GLOBAL NUMBER OF ELEMENTS
   INTEGER MGL                !!GLOBAL NUMBER OF NODES
   INTEGER IBFW_GL            !!GLOBAL NUMBER OF GROUNDWATER NODES
   INTEGER NUMQBC_GL          !!GLOBAL NUMBER OF FRESHWATER INFLOW NODES
   INTEGER NOBCGEO_GL         !!GLOBAL NUMBER OF OPEN BOUNDARY 
   INTEGER NDRFT_GL           !!GLOBAL NUMBER OF LAGRANGIAN TRACKING PARTICLES 

   INTEGER N                  !!LOCAL NUMBER OF ELEMENTS 
   INTEGER M                  !!LOCAL NUMBER OF NODES
   INTEGER IBFW               !!LOCAL NUMBER OF GROUNDWATER NODES
   INTEGER NUMQBC             !!LOCAL NUMBER OF FRESHWATER INFLOW NODES
   INTEGER NOBCGEO            !!LOCAL NUMBER OF OPEN BOUNDARY 
   INTEGER NDRFT              !!LOCAL NUMBER OF LAGRANGIAN TRACKING PARTICLES
   INTEGER NISBCE_1           !!LOCAL NUMBER OF ELEMENTS WITH ISBCE = 1
   INTEGER NISBCE_2           !!LOCAL NUMBER OF ELEMENTS WITH ISBCE = 2
   INTEGER NISBCE_3           !!LOCAL NUMBER OF ELEMENTS WITH ISBCE = 3

   INTEGER KB                 !!NUMBER OF SIGMA LEVELS
   INTEGER KBM1               !!NUMBER OF SIGMA LEVELS-1
   INTEGER KBM2               !!NUMBER OF SIGMA LEVELS-2
   INTEGER MYID               !!UNIQUE PROCESSOR ID (1 => NPROCS)
   INTEGER KSL                !!NUMBER OF STANDARD SEA LEVELS 
   INTEGER NPROCS             !!NUMBER OF PROCESSORS
   INTEGER NE                 !!NUMBER OF UNIQUE EDGES (LOCAL DOMAIN ONLY)
   INTEGER NCV                !!NUMBER OF INTERNAL CONTROL VOLUMES (EXTENDED LOCAL ONLY)
   
   INTEGER NCV_I              !!NUMBER OF INTERNAL CONTROL VOLUMES (LOCAL ONLY)
   INTEGER NT                 !!TOTAL OF LOCAL INTERNAL + HALO ELEMENTS
   INTEGER MT                 !!TOTAL OF LOCAL INTERNAL + HALO NODES
   INTEGER MX_NBR_ELEM        !!MAX NUMBER OF ELEMENTS SURROUNDING A NODE
!----------------Node, Boundary Condition, and Control Volume-----------------------!

   INTEGER, ALLOCATABLE :: NV(:,:),NV2(:,:)    !!NODE NUMBERING FOR ELEMENTS
   INTEGER, ALLOCATABLE :: NBE(:,:)            !!INDICES OF ELMNT NEIGHBORS
   INTEGER, ALLOCATABLE :: NTVE(:)      
   INTEGER, ALLOCATABLE :: NTSN(:)      
   INTEGER, ALLOCATABLE :: ISONB(:)            !!NODE MARKER = 0,1,2
   INTEGER, ALLOCATABLE :: ISBC(:)     
   INTEGER, ALLOCATABLE :: ISBCE(:)     
   INTEGER, ALLOCATABLE :: IEC(:,:)
   INTEGER, ALLOCATABLE :: IENODE(:,:)
   INTEGER, ALLOCATABLE :: NBSN(:,:)
   INTEGER, ALLOCATABLE :: NIEC(:,:)
   INTEGER, ALLOCATABLE :: NTRG(:)
   INTEGER, ALLOCATABLE :: NBVE(:,:)
   INTEGER, ALLOCATABLE :: NBVT(:,:)
   INTEGER, ALLOCATABLE :: LISBCE_1(:)          !!LIST OF ELEMENTS WITH ISBCE=1
   INTEGER, ALLOCATABLE :: LISBCE_2(:)          !!LIST OF ELEMENTS WITH ISBCE=2
   INTEGER, ALLOCATABLE :: LISBCE_3(:)          !!LIST OF ELEMENTS WITH ISBCE=3
   REAL(SP),ALLOCATABLE :: DLTXC(:)
   REAL(SP),ALLOCATABLE :: DLTYC(:)
   REAL(SP),ALLOCATABLE :: DLTXYC(:)
   REAL(SP),ALLOCATABLE :: DLTXE(:)
   REAL(SP),ALLOCATABLE :: DLTYE(:)
   REAL(SP),ALLOCATABLE :: DLTXYE(:)
   REAL(SP),ALLOCATABLE :: SITAC(:) 
   REAL(SP),ALLOCATABLE :: SITAE(:) 
   REAL(SP),ALLOCATABLE :: XIJC(:) 
   REAL(SP),ALLOCATABLE :: YIJC(:)
   REAL(SP),ALLOCATABLE :: XIJE(:,:) 
   REAL(SP),ALLOCATABLE :: YIJE(:,:) 
   REAL(SP),ALLOCATABLE :: EPOR(:)            !!ELEMENT FLUX POROSITY (=0. IF ISBCE = 2)
   INTEGER, ALLOCATABLE :: IBCGEO(:)        !!LOCAL GEOSTROPHIC FRICTION CORRECTION NODES
   INTEGER, ALLOCATABLE :: N_ICELLQ(:,:)    !!FLUX ANGLE 

!--------------------------Global Grid Variables------------------------------------!

REAL(SP), ALLOCATABLE :: XG(:),XG2(:)              !!GLOBAL X-COORD AT NODE 
REAL(SP), ALLOCATABLE :: YG(:),YG2(:)               !!GLOBAL X-COORD AT NODE 
REAL(SP), ALLOCATABLE :: HG(:),HG2(:)               !!GLOBAL DEPTH AT NODE 
REAL(SP), ALLOCATABLE :: XCG(:)              !!GLOBAL X-COORD AT FACE CENTER 
REAL(SP), ALLOCATABLE :: YCG(:)              !!GLOBAL X-COORD AT FACE CENTER 
!--------------------------Grid Metrics---------------------------------------------!

REAL(SP)              :: VXMIN,VYMIN,VXMAX,VYMAX
REAL(SP), ALLOCATABLE :: XC(:)               !!X-COORD AT FACE CENTER 
REAL(SP), ALLOCATABLE :: YC(:)               !!Y-COORD AT FACE CENTER
REAL(SP), ALLOCATABLE :: VX(:)               !!X-COORD AT GRID POINT
REAL(SP), ALLOCATABLE :: VY(:)               !!Y-COORD AT GRID POINT
REAL(SP), ALLOCATABLE :: ART(:)              !!AREA OF ELEMENT
REAL(SP), ALLOCATABLE :: ART1(:)             !!AREA OF NODE-BASE CONTROl VOLUME
REAL(SP), ALLOCATABLE :: ART2(:)             !!AREA OF ELEMENTS AROUND NODE

CHARACTER(LEN=255):: FNAME1,FNAME2,CASENAME

REAL(SP),PARAMETER    :: SPG_R=1000,SPG_C=0.000,DAM_HEIGHT=8

END MODULE ALL_VARS